### PR TITLE
Implement TinyTween.

### PR DESCRIPTION
**Pull request by GravityScriptsV2**
As you may be asking whats tinytween? it provides animations to be used with elements such as rectangles. For exampling flashing of a rectangle and changing the color can be done. Would love this to be added to this mod, so I can relay on it within my mod. Thanks :)

### CODE REVIEW

**Comment by Michael21107** [comment]
@alexguirre please come back

**Comment by Michael21107** [comment]
> As you may be asking whats tinytween? it provides animations to be used with elements such as rectangles. For exampling flashing of a rectangle and changing the color can be done. Would love this to be added to this mod, so I can relay on it within my mod. Thanks :)

did u try inheritance?

**Comment by alexguirre** [comment]
I agree that tweening is useful in general, but I don't think it needs to be included with RNUI, when it doesn't really integrate with the rest of the project in any way. Plugin devs can include these classes or similar functionality in their plugins if they need them.

Also this seems to be missing the license of the original code? Not sure what the original source is but found this that includes a MIT license in the beginning: https://gist.github.com/nanexcool/09871ddf4b4baaf6aa32
In the future, please include this kind of licenses in NOTICE.md.

**Comment by Michael21107** [comment]
@GravityScriptsV2

**Pull request closed without merging**
